???

diff --git a/Projects/Makefile b/Projects/Makefile
--- a/Projects/Makefile
+++ b/Projects/Makefile
@@ -7,7 +7,11 @@ run-unit:
 unit-test:
 	for x in * \
 	do \
-		{ cd $$x && mvn test && cd ..} || { echo "Failed at $${x}" } \
+		{ \
+			cd $$x && mvn test && cd .. \
+		} || { \
+			echo "Failed at $${x}"  \
+		} \
 	done;
 
 unit-tests-folder:
